#!/bin/sh
# Compile Sass/Compass/Susy Compressed
compass compile --output-style compressed --force
sprocketize
rsync -av sjs/polyfill/ js/polyfill
function gzipkeep {
for file in $1
do
	if [ -f "$1" ] ; then
		gzip -9 -c -- "$file" > "$file.gz"
	fi
done
}
gzipkeep js/polyfill/*
gzipkeep css/*
